# ~/ansible-cluster/hosts.ini
[db]
db-client-01 ansible_host=192.168.100.61
db-client-02 ansible_host=192.168.100.62

[api]
api-internal-01 ansible_host=192.168.100.63
api-internal-02 ansible_host=192.168.100.64

[web]
web-01 ansible_host=192.168.100.65
web-02 ansible_host=192.168.100.66

[all_servers:children]
db
api
web